spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ustinterview.chhigymanwl1.ap-south-1.rds.amazonaws.com:3306/ustinterviews
    username: root
    password: Aysha2000
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true